image: maven:3.9.16-eclipse-temurin-25

variables:
  MAVEN_OPTS: "-Dhttp.keepAlive=false -DinteractiveMode=false -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - package

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.repo.local=.m2/repository clean compile

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.repo.local=.m2/repository test

package_job:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.repo.local=.m2/repository package -DskipTests
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - target/*.jar
    expire_in: 1 week